version: "3.8"
services:
  app:
    build: ansh144/todo-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./app:/app
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: