name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Image
      run: |
        docker buildx build \
        --platform linux/amd64 \
        -t ${{ secrets.DOCKER_USERNAME }}/todo-app \
        --push ./app

    - name: Setup SSH
      run: |
        echo "${{ secrets.EC2_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Deploy to EC2
      run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user

            # always fresh copy (simple + reliable)
            rm -rf app
            git clone https://github.com/anshtyagi-14/multi-container-app app
            rm -f docker-compose.yml
            cd app

            docker-compose down
            docker-compose up -d
          EOF
